ueRoutingInfo:
  - SUPI: imsi-2089300000001
    AN: 172.16.10.2
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

  - SUPI: imsi-2089300000002
    AN: 172.16.10.2
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

  - SUPI: imsi-2089300000003
    AN: 172.16.10.2
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

  - SUPI: imsi-2089300000004
    AN: 172.16.10.2
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

  - SUPI: imsi-2089300000005
    AN: 172.16.10.2
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

routeProfile:
  MEC1:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 60.60.0.1 8080 to any
