ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: upf.free5gc
    PathList:
      - DestinationIP: 60.60.0.101
        UPF: !!seq
          - UPF

      - DestinationIP: 60.60.0.103
        UPF: !!seq
          - UPF

  - SUPI: imsi-2089300007486
    AN: upf.free5gc
    PathList:
      - DestinationIP: 10.0.0.10
        UPF: !!seq
          - UPF

      - DestinationIP: 10.0.0.11
        UPF: !!seq
          - UPF

routeProfile:
  MEC1:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 60.60.0.1 8080 to any
